### ISSUE TITLE
Build correctly, but still computing on CPU

### ISSUE THREAD

**Issue by valcarce01** [JuliaGPU/AMDGPU.jl#117]
For understanding the problem, this is the CPU consumption metrics:
```@time rand(5000, 5000) * rand(5000, 5000)```
![Screenshot from 2021-03-21 15-51-26](https://user-images.githubusercontent.com/47260541/111909386-61a92a00-8a5d-11eb-932a-2448914508a9.png)
(as shown and expected, the CPU consumption grows)

Now, using the AMDGPU library and the HSAArrays:
```@time HSAArray(rand(5000, 5000)) * HSAArray(rand(5000, 5000))```
Should be executing on the GPU, right? Well, it's not. When this code is run, it executes on the CPU, but at a lower power consumption:
![image](https://user-images.githubusercontent.com/47260541/111909442-97e6a980-8a5d-11eb-90e1-29dd91a3fd2d.png)

You can appreciate that is a little slope in the powe usage (on the CPU) at the end of the graphics, but no change at all on the GPU.

**Comment by jpsamaroo** [comment]
You're using a version of AMDGPU that's too old. Recent versions of AMDGPU removed the `HSAArray` in favor of the `ROCArray`, so update AMDGPU (0.2.3 is the latest release) and do `@time ROCArray(rand(5000, 5000)) * ROCArray(rand(5000, 5000))`. Note that you'll need to have rocBLAS installed for this to work properly (since it's doing a matrix-multiply, which uses BLAS).
