### ISSUE TITLE
Addition of AMDGPU.functional() (equivalent to CUDA.functional())

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/AMDGPU.jl#198]
Would it be feasible to add a function `AMDGPU.functional()` that is equivalent to `CUDA.functional()`?
`CUDA.functional()` is extremely useful for conditional usage of CUDA, depending on whether there is a CUDA-capable GPU and the CUDA stack properly installed... in brief, depending on whether CUDA is functional (see [in this discourse post](https://discourse.julialang.org/t/how-to-add-cuda-as-optional-dependency/73077/7?u=samo) for more context).

`AMDGPU.has_rocm_gpu()` lets query if there is a usable GPU available, but not if the AMDGPU stack was properly installed, i.e. AMDGPU ready to be used.

**Comment by jpsamaroo** [comment]
"Functional" is somewhat multi-faceted in AMDGPU, because not all functionality is required for general usage. For example, HIP is now optional (only necessary when using rocBLAS et. al), and rocBLAS et. al are also optional. Additionally, in the future, device libraries could be made optional, and we could even allow compiling AMDGPU kernels without the presence of any device interface libraries (just using AMDGPU to drive LLVM).

So my question would be, can we implement `AMDGPU.functional()` in such a way that we can query which pieces are available? Maybe we should take an optional `Symbol` argument, which could be `:hsa`, `:hip`, `:rocblas`, etc., to query an individual component (and any required dependencies), with a plain `AMDGPU.functional()` querying all of the currently-usable components?
