### ISSUE TITLE
mapreducedim! is not implemented for AnyROCArray Types

### ISSUE THREAD

**Issue by matinraayai** [JuliaGPU/AMDGPU.jl#234]
Hello,
```GPUArray.mapreducedim!``` should be implemented for ```AnyROCArray``` instead of the more specific type of ```ROCArray```. Is there a way for ```AnyROCArray``` to be adapted to ```ROCArray```, so that this function is implemented for ```AnyROCArray```?
Thanks

**Comment by jpsamaroo** [comment]
As a stop-gap we can just convert to a dense `ROCArray` and then switch back the type after. @maleadt any recommendations?

**Comment by maleadt** [comment]
Why not implement `mapreducedim!` for AnyROCArray? Works for CUDA: https://github.com/JuliaGPU/CUDA.jl/blob/0060ea6f29b7dcfc5563dae868c11feb5d26281e/src/mapreduce.jl#L169-L171=, as these types are 'guaranteed' to work in a kernel.

**Comment by matinraayai** [comment]
@maleadt should changing the function prototype to accept ```AnyROCArray``` work directly in theory?

**Comment by maleadt** [comment]
I think so, but I'm not very familiar with AMDGPU.jl or it's mapreduce implementation. Try it out and see what breaks?

**Comment by matinraayai** [comment]
@maleadt @jpsamaroo I've tried it before, but the problem is that the AMDGPU implementation queries the ROCm device associated with the ROCArray using its buffer field here:
https://github.com/JuliaGPU/AMDGPU.jl/blob/99967b75deb4d78c12236e9a77943b4e0294af35/src/mapreduce.jl#L133
I have to look into it, but I don't think it will be as simple as changing the function prototype.

**Comment by maleadt** [comment]
Then https://github.com/JuliaGPU/Adapt.jl/pull/52 would probably be useful.

**Comment by matinraayai** [comment]
@maleadt it looks good, but do you have an ETA on when it will merge?
Also it seems like the CUDA version also queries the current thread's device, which might not correspond to the actual device the array resides on. I think when merged, we can use this feature to fix bugs in both CUDA.jl and AMDGPU.jl. 
https://github.com/JuliaGPU/CUDA.jl/blob/c1ef162c06d78c4b5cf31914fa1acf7db34eb7f5/src/mapreduce.jl#L174

**Comment by maleadt** [comment]
No ETA on that change. You should probably use an `agent` function instead and define it on a couple of common wrappers, like oneAPI.jl does for its `device` function: https://github.com/JuliaGPU/oneAPI.jl/blob/9a43fb6fbf0ef20ffba34daef4b7ff44e7ed01c8/src/array.jl#L370-L371=



> Also it seems like the CUDA version also queries the current thread's device, which might not correspond to the actual device the array resides on.

It's currently up to the user to make sure to use the correct array on its respective device. I don't think I'll make it automatic, since it's not clear what to do if multiple devices are involved. It's also possible to create arrays whose memory is accessible from other devices.

**Comment by maleadt** [comment]
Ah yeah, we disabled those subtypes in Adapt.jl (which the Any* types are based on): https://github.com/JuliaGPU/Adapt.jl/blob/d9f852a61ee42258e543f5ff3b28e1f3abbb48bc/src/wrappers.jl#L86-L90=. That's because Adapt.jl used to be only used by CUDA.jl, where CuArray is used to encode views and reshapes (i..e, without using the array wrappers). Either we make it 'mandatory' for users of the Any* union types to handle SubArray/Reinterpret/Reshape themselves, or we should generalize Adapt.jl

**Comment by matinraayai** [comment]
@maleadt are CuSubArrays currently count as AnyCuArrays? Can I do the same thing CUDA.jl is doing to make AMDGPU support this type hierarchy? Idealy I want it in Adapt.jl because it seems useful but for now I need the workaround for our project.

**Comment by matinraayai** [comment]
@jpsamaroo @maleadt not sure I'm following. What exactly is the preferred course of action here?

**Comment by christophernhill** [comment]
@jpsamaroo and @maleadt could we do a quick zoom to sync up on this - I think its a quick fix.

**Comment by matinraayai** [comment]
@jpsamaroo I've created a pull request for this:
https://github.com/JuliaGPU/AMDGPU.jl/pull/241
Let me know when your device detection code for AMDGPU is added to master so that I can modify my PR accordingly.
Thanks,
Matin
