### ISSUE TITLE
Add AMDGPU.jl equivalent to CUDA.CuDynamicSharedArray (and CUDA.CuStaticSharedArray)

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/AMDGPU.jl#304]
Would it be possible to add an equivalent to [`CUDA.CuDynamicSharedArray`](https://cuda.juliagpu.org/stable/api/kernel/#CUDA.CuDynamicSharedArray) (a `CUDA.CuStaticSharedArray` equivalent we don't need, but would certainly be expected to be available by some users)?

**Comment by jpsamaroo** [comment]
Yes, this should be totally possible with Julia 1.9/nightly, thanks to https://reviews.llvm.org/D82496 (this doesn't appear to work on 1.7, and 1.8 is unsupported). We can call `AMDGPU.Device.alloc_local(:my_shmem, Float32, 0)` to allocate LDS dynamically (the 0 size is treated as meaning that we don't know how much LDS we need until runtime). We then need to adjust the group segment size that we report to the HSA runtime (https://github.com/JuliaGPU/AMDGPU.jl/blob/13264a3fb6d2b76601b83d626f881670a7c40e6c/src/kernel.jl#L93-L95) so that the hardware allocates enough LDS for us. That's going to require a `localmem` knob for `@roc`, like how `@cuda` has `shmem`.
